### Getting the data

In [9]:
pd.__version__

'3.1.0'

In [2]:
import numpy as np 
import pandas as pd 

url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"
df = pd.read_csv(url) 

df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

### Q2. Records count

In [12]:
df.shape[0]

10000

### Q3. Fuel types

In [4]:
df.fuel_type.nunique()

3

### Q4. Missing values

In [6]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

### Q5. Max fuel efficiency

In [7]:
df.groupby('origin').max()

,model_year,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
origin,,,,,,,,,,
Asia,2024,Hybrid,Rear-wheel drive,5,3020,8,334.0,5280,23.8,41.2
Europe,2024,Hybrid,Rear-wheel drive,5,2870,8,332.0,5040,23.4,39.4
USA,2024,Hybrid,Rear-wheel drive,5,3110,8,334.0,5460,22.8,38.2

### Q6. Median value of horsepower

In [13]:
# 1. Mediana antes de rellenar
mediana_antes = df['horsepower'].median()

# 2. Valor más frecuente (la moda). mode() devuelve una lista, por eso el [0]
moda = df['horsepower'].mode()[0]

# 3. Rellenar los nulos con la moda
df['horsepower'] = df['horsepower'].fillna(moda)

# 4. Mediana después
mediana_despues = df['horsepower'].median()

print(mediana_antes, moda, mediana_despues)

254.0 252.0 252.0

### Q7. Sum of weights

In [14]:
# Coches de Asia
asia = df[df['origin'] == 'Asia']

# Solo dos columnas y las 7 primeras filas, como array de NumPy
X = asia[['vehicle_weight', 'model_year']].head(7).values

# X traspuesta por X
XTX = X.T @ X

# Invertir
XTX_inv = np.linalg.inv(XTX)

# Vector y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# w = (XTX)^-1 · X^T · y
w = XTX_inv @ X.T @ y

w.sum()

np.float64(0.36919696904925486)